AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  image-hosting-service

  Sample SAM Template for image-hosting-service

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs12.x
  Api:
    BinaryMediaTypes:
    - multipart~1form-data

Parameters:
  S3Bucket:
    Type: String
    Default: upscale-image-hosting

Resources:
  ImageHostApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: prod
  ImageHostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      CodeUri: application/
      Policies:
        - S3WritePolicy:
            BucketName: !Ref S3Bucket
      Environment:
        Variables:
          BUCKET_NAME: !Ref S3Bucket
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /upload
            Method: post
            RestApiId:
              Ref: ImageHostApi